apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  app-configuracao 
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-configuracao
          image: kubedevio/app-variaveis-ambiente:v1
          ports: 
          - containerPort: 3000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME_CONFIG
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_VERSION_CONFIG
            - name: APP_AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_AUTHOR_CONFIG

---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30000
      